### PR TITLE
fix(audio): await AudioContext.resume() before playing confirmation chime

### PR DESCRIPTION
**Pull request by OPS-PIvers**
## Root cause

`CatalystWidget.tsx` and `StarterPack/Widget.tsx` both fired `ctx.resume()` without awaiting it, then immediately called `playCleanUp()`:

```js
if (ctx && ctx.state === 'suspended') { void ctx.resume(); }  // fire-and-forget
playCleanUp();  // checks ctx.state === 'suspended' and no-ops if still true
```

`AudioContext.resume()` is async and does not flip `ctx.state` synchronously. `playCleanUp()`'s own guard (`if (!ctx || ctx.state === 'suspended') return;`) ran while `ctx.state` was still `'suspended'`, silently dropping the confirmation chime every time the shared `AudioContext` starts out suspended (the normal state on first user interaction, per browser autoplay policy). `DiceWidget.tsx` elsewhere in the codebase already does this correctly (`await ctx.resume()` before checking state), confirming this was an inconsistent, incorrect pattern duplicated in two places.

## Fix

Added `playCleanUpUnlocked()` to the shared `components/widgets/StarterPack/audioUtils.ts` — awaits `ctx.resume()` (with a safe catch) before calling `playCleanUp()`. Both `CatalystWidget.handleExecute` and `StarterPackWidget.handleExecute` now `await playCleanUpUnlocked()` instead of the broken manual resume/play sequence.

## Rejected band-aid

Adding `await` inline at each of the two call sites was considered and rejected — it leaves the same pattern duplicated twice. The actual fix (knowledge of "resume must be awaited before checking state") belongs in the shared audio helper, not repeated at each caller.

## Regression test

`components/widgets/StarterPack/audioUtils.test.ts` (new), following the existing `tests/utils/timeToolAudio.test.ts` AudioContext-mocking convention.

**Fail-before / pass-after** (independently re-verified by the orchestrator): swapped in the pre-fix `audioUtils.ts` — both new tests fail (`playCleanUpUnlocked is not a function`); restored, both pass.

## Verification

- `pnpm run validate` — clean (orchestrator-independent run; one unrelated pre-existing flaky test, `useRosters.test.ts`, was seen under concurrent-worktree CPU contention on the first pass — confirmed unrelated to this change and passes in isolation and on a clean re-run).
- `pnpm run build` — passes (orchestrator-independent run).

## Risk: contained

Isolated to two widgets' click handlers plus a new shared helper; no change to existing exported behavior of `playCleanUp`/`getAudioCtx`.

---
_Generated by [Claude Code](https://claude.ai/code/session_01VEJTpeRWqRCPMhEfKbDNPZ)_

### CODE REVIEW

File: components/widgets/Catalyst/CatalystWidget.tsx [hunk 1]
```diff
@@ -24,19 +21,14 @@ export const CatalystWidget: React.FC<{ widget: WidgetData }> = ({
...
 
-    const ctx = getAudioCtx();
-    if (ctx && ctx.state === 'suspended') {
-      void ctx.resume();
-    }
-
     executeRoutine(routine, addWidget);
 
-    playCleanUp();
+    await playCleanUpUnlocked();
```
[the remark this answers is not in the document]
Comment (OPS-PIvers) [reply components/widgets/Catalyst/CatalystWidget.tsx]: Fixed in the latest commit — `handleExecute` is now synchronous and calls `void playCleanUpUnlocked()`, so the confetti fires instantly instead of waiting on the internal `ctx.resume()` await. The audio still unlocks and plays correctly (audioUtils tests 2/2 green).

---
_Generated by [Claude Code](https://claude.ai/code)_

File: components/widgets/StarterPack/Widget.tsx [hunk 2]
```diff
@@ -18,18 +18,12 @@ export const StarterPackWidget = ({ isStudentView }: WidgetComponentProps) => {
...
-      void ctx.resume();
-    }
-
+  const handleExecute = async (pack: StarterPack) => {
     // Call the execution logic with cleanSlate=true
     executePack(pack, true, addWidget, deleteAllWidgets);
 
     // Audio and visual cues
-    playCleanUp();
+    await playCleanUpUnlocked();
```
[the remark this answers is not in the document]
Comment (OPS-PIvers) [reply components/widgets/StarterPack/Widget.tsx]: Fixed in the latest commit — same change applied here: `handleExecute` is now synchronous and uses `void playCleanUpUnlocked()` so the confetti isn't blocked on the audio resume.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Review by OPS-PIvers — COMMENTED** [review]
## Automated Code Review

**Date:** 2026-07-07

### Summary
Fixes a silently-dropped confirmation chime in Catalyst and StarterPack widgets by adding a shared `playCleanUpUnlocked()` helper that awaits `ctx.resume()` before playing. Correctly centralizes the "resume must be awaited before checking state" knowledge in the shared audio util rather than duplicating it at each call site.

### Code Quality
✓ No issues found. In the latest commit `handleExecute` was also made synchronous with `void playCleanUpUnlocked()` (per review feedback) so the confetti isn't blocked on the audio resume.

### Widget Standards
✓ No issues found — front-face content unchanged; only click handlers touched.

### Admin Config Standards
✓ Not applicable.

### Firestore & Security
✓ No issues found.

### Regression Risk
✓ Low risk. Isolated to two click handlers plus a new shared helper; existing `playCleanUp`/`getAudioCtx` exports are unchanged.

### Missing Tests
✓ Adequate — new `audioUtils.test.ts` covers the unlock-then-play path following the existing AudioContext-mock convention (2/2 pass locally).

### Overall
**Merge readiness:** Ready
Small, correct fix that matches the already-correct `DiceWidget` pattern.

---
_This review was generated automatically. All findings should be verified by a human before merging._

---
_Generated by [Claude Code](https://claude.ai/code)_

File: components/widgets/StarterPack/audioUtils.ts [hunk 3]
```diff
@@ -19,6 +19,21 @@ export const getAudioCtx = () => {
   return audioCtx;
 };
 
+// Awaits ctx.resume() before playing — resume() doesn't flip ctx.state
+// synchronously, so a fire-and-forget resume left playCleanUp's own
+// suspended-state guard silently skipping the chime on first use.
```
Comment (OPS-PIvers) [inline components/widgets/StarterPack/audioUtils.ts]: CLAUDE.md: *"one short line max"* — 3-line block should collapse to one:

```suggestion
// Awaits ctx.resume() before playing; fire-and-forget resume doesn't flip ctx.state synchronously.
export const playCleanUpUnlocked = async (): Promise<void> => {
```

---
_Generated by [Claude Code](https://claude.ai/code)_

**Review by OPS-PIvers — COMMENTED** [review]
CLAUDE.md comment-length sweep — one finding.

---
_Generated by [Claude Code](https://claude.ai/code)_

File: components/widgets/StarterPack/audioUtils.ts (hunk 3 above)
Comment (OPS-PIvers) [reply components/widgets/StarterPack/audioUtils.ts]: Fixed — the 3-line block was collapsed to the single-line suggested form: `// Awaits ctx.resume() before playing; fire-and-forget resume doesn't flip ctx.state synchronously.` Thread is outdated because this landed in the same commit batch that addressed the `void playCleanUpUnlocked()` suggestions above.

---
_Generated by [Claude Code](https://claude.ai/code)_
